
const RIDE_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
};

const INCIDENT_TYPES = {
  CRASH: 'CRASH',
  MANUAL_SOS: 'MANUAL_SOS',
  FALL: 'FALL',
};

const CONFIRMATION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  AUTO_TRIGGERED: 'AUTO_TRIGGERED',
};

const NOTIFICATION_TYPES = {
  SOS: 'SOS',
  CRASH: 'CRASH',
  SYSTEM: 'SYSTEM',
};

const NOTIFICATION_CHANNELS = {
  PUSH: 'PUSH',
  EMAIL: 'EMAIL',
  BOTH: 'BOTH',
};

const NOTIFICATION_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  DELIVERED: 'DELIVERED',
};

module.exports = {

  RIDE_STATUS,
  INCIDENT_TYPES,
  CONFIRMATION_STATUS,
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUS,
};
